<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Produk;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            ["name" => "Almond Milk 160 gr", "category" => "Umum"],
            ["name" => "Almond Milk 320 gr", "category" => "Umum"],
            ["name" => "Almond Milk Matcha 160 gr", "category" => "Umum"],
            ["name" => "Almond Milk Matcha 320 gr", "category" => "Umum"],
            ["name" => "Almond Skinless 250", "category" => "Umum"],
            ["name" => "Almond Sliced 250", "category" => "Umum"],
            ["name" => "Almond Sliced 500", "category" => "Umum"],
            ["name" => "Apricot 250", "category" => "Umum"],
            ["name" => "Apricot 500", "category" => "Umum"],
            ["name" => "Apricot 1000", "category" => "Umum"],
            ["name" => "Baked Cashew Nut 300", "category" => "Umum"],
            ["name" => "Blueberry 100", "category" => "Umum"],
            ["name" => "Blueberry 250", "category" => "Umum"],
            ["name" => "Blueberry 500", "category" => "Umum"],
            ["name" => "Blueberry 1000", "category" => "Umum"],
            ["name" => "Chia Seed 300", "category" => "Umum"],
            ["name" => "ChocoPump", "category" => "Umum"],
            ["name" => "Coconut Flakes 300", "category" => "Umum"],
            ["name" => "Cranberry 100", "category" => "Umum"],
            ["name" => "Cranberry 250", "category" => "Umum"],
            ["name" => "Cranberry 500", "category" => "Umum"],
            ["name" => "Cranberry 1000", "category" => "Umum"],
            ["name" => "Gojiberry 100", "category" => "Umum"],
            ["name" => "Gojiberry 250", "category" => "Umum"],
            ["name" => "Gojiberry 500", "category" => "Umum"],
            ["name" => "Gojiberry 1000", "category" => "Umum"],
            ["name" => "Golden Raisin 300", "category" => "Umum"],
            ["name" => "Hazelnut 100", "category" => "Umum"],
            ["name" => "Hazelnut 250", "category" => "Umum"],
            ["name" => "Hazelnut 500", "category" => "Umum"],
            ["name" => "Honey Garlic Almond 1000", "category" => "Umum"],
            ["name" => "Honey Garlic Almond 300", "category" => "Umum"],
            ["name" => "Hurly Burly Nut 150", "category" => "Umum"],
            ["name" => "Hurly Burly Nut 300", "category" => "Umum"],
            ["name" => "Macadamia 100", "category" => "Umum"],
            ["name" => "Macadamia 250", "category" => "Umum"],
            ["name" => "Macadamia 500", "category" => "Umum"],
            ["name" => "MASTERMIND LARGE - LARGE", "category" => "Umum"],
            ["name" => "MASTERMIND LARGE - MEDIUM", "category" => "Umum"],
            ["name" => "MASTERMIND LARGE - SMALL", "category" => "Umum"],
            ["name" => "Natural Almond 100", "category" => "Umum"],
            ["name" => "Natural Almond 1000", "category" => "Umum"],
            ["name" => "Natural Almond 250", "category" => "Umum"],
            ["name" => "Natural Almond 500", "category" => "Umum"],
            ["name" => "Nutty Crunch 250", "category" => "Umum"],
            ["name" => "Pistachio 100", "category" => "Umum"],
            ["name" => "Pistachio 250", "category" => "Umum"],
            ["name" => "Pistachio 500", "category" => "Umum"],
            ["name" => "Pumpkin Seed 1000", "category" => "Umum"],
            ["name" => "Pumpkin Seed 250", "category" => "Umum"],
            ["name" => "Pumpkin Seed 500", "category" => "Umum"],
            ["name" => "Roasted Almond 1000", "category" => "Umum"],
            ["name" => "Roasted Almond 300", "category" => "Umum"],
            ["name" => "Sunflower Seed 1000", "category" => "Umum"],
            ["name" => "Sunflower Seed 250", "category" => "Umum"],
            ["name" => "Sunflower Seed 500", "category" => "Umum"],
            ["name" => "Walnut 100", "category" => "Umum"],
            ["name" => "Walnut 250", "category" => "Umum"],
            ["name" => "Walnut 500", "category" => "Umum"],
            ["name" => "Walnut 1000", "category" => "Umum"],
            ["name" => "Gladly Snack 180", "category" => "Umum"],
            ["name" => "Nutty Crunch 115", "category" => "Umum"],
            ["name" => "Roasted Almond 115", "category" => "Umum"],
            ["name" => "Wonder Bar", "category" => "Umum"],
            ["name" => "Honey Garlic Almond 115", "category" => "Umum"],
            ["name" => "Nutty Crunch 100", "category" => "Umum"],
            ["name" => "Roasted Almond 100", "category" => "Umum"],
            ["name" => "Honey Garlic Almond 100", "category" => "Umum"],
            ["name" => "Gladly Snack 100", "category" => "Umum"],
            ["name" => "Apricot 100", "category" => "Umum"],
            ["name" => "Sunflower 100", "category" => "Umum"],
            ["name" => "Blueberry 50", "category" => "Umum"],
            ["name" => "Cholesterol Pro-Shot", "category" => "Umum"],
            ["name" => "Keripik buah", "category" => "Umum"],
            ["name" => "Keripik sayur", "category" => "Umum"],
            ["name" => "Keripik buah extra stroberi", "category" => "Umum"],
            ["name" => "Keripik buah stroberi", "category" => "Umum"],
            ["name" => "Keripik buah fig", "category" => "Umum"],
            ["name" => "Keripik buah stroberi & fig", "category" => "Umum"],
            ["name" => "Okra chips", "category" => "Umum"],
            ["name" => "Vegy Baby", "category" => "Umum"],
            ["name" => "Granola Macadamia", "category" => "Umum"],
            ["name" => "Granola Pumpkin", "category" => "Umum"],
            ["name" => "Teri Crispy", "category" => "Umum"],
            ["name" => "Fruity Mix 1100 ML", "category" => "Umum"],
            ["name" => "Fruity Mix Special", "category" => "Umum"],
            ["name" => "Veggie Mix 1100 ML", "category" => "Umum"],
            ["name" => "Paket Mix Foil", "category" => "Umum"],
            ["name" => "Almond Milk Ketan Hitam 160 gr", "category" => "Umum"],
            ["name" => "Almond Milk Ketan Hitam 320 gr", "category" => "Umum"],
            ["name" => "Keripik Daging", "category" => "Umum"],
            ["name" => "Serbuk Daging", "category" => "Umum"],
            ["name" => "Serbuk Telur", "category" => "Umum"],
            ["name" => "Serbuk Hati Ayam", "category" => "Umum"],
            ["name" => "Serbuk Hati Sapi", "category" => "Umum"],
            ["name" => "Nanas Chips", "category" => "Umum"],
            ["name" => "Nangka Chips", "category" => "Umum"],
            ["name" => "Salak Chips", "category" => "Umum"],
            ["name" => "Pisang Chips", "category" => "Umum"],
            ["name" => "Fruit Chips 1 kg", "category" => "Umum"],
            ["name" => "Apel Chips", "category" => "Umum"],
            ["name" => "Wortel Chips", "category" => "Umum"],
            ["name" => "Ubi madu", "category" => "Umum"],
            ["name" => "Ubi ungu", "category" => "Umum"],
            ["name" => "Pumpkin Chips", "category" => "Umum"],
            ["name" => "Baby Jackfruit", "category" => "Umum"],
            ["name" => "Edamame 30 gr", "category" => "Umum"],
            ["name" => "Edamame 350 ml", "category" => "Umum"],
            ["name" => "Edamame 1100ml", "category" => "Umum"],
            ["name" => "Edamame 500ml", "category" => "Umum"],
            ["name" => "Edamame 200ml", "category" => "Umum"],
            ["name" => "Edamame 300 ml", "category" => "Umum"],
            ["name" => "Kiwi Chips", "category" => "Umum"],
            ["name" => "Mushroom Chips", "category" => "Umum"],
            ["name" => "Jujube Chips", "category" => "Umum"],
            ["name" => "Golden Green Edamame 200ml", "category" => "Umum"],
            ["name" => "Golden Green Edamame 500ml", "category" => "Umum"],
            ["name" => "Cinnamon Banana Bite", "category" => "Umum"],
            ["name" => "SP Okra", "category" => "Umum"],
            ["name" => "Fruit Chips 350 ml", "category" => "Umum"],
            ["name" => "Stroberi Chips 350 ml", "category" => "Umum"],
            ["name" => "Fig Chips 350 ml", "category" => "Umum"],
            ["name" => "Veggie Chips 350 ml", "category" => "Umum"],
            ["name" => "Biscotti", "category" => "Umum"],
            ["name" => "Fruit Chips 300 ml", "category" => "Umum"],
            ["name" => "Veggie Chips 300 ml", "category" => "Umum"],
            ["name" => "Strawberry Chips 300 ml", "category" => "Umum"],
            ["name" => "Strawberry Chips 500 ml", "category" => "Umum"],
            ["name" => "Garlic Chips", "category" => "Umum"],
            ["name" => "Fruit Chips 500 ml", "category" => "Umum"],
            ["name" => "Veggie Chips 500 ml", "category" => "Umum"],
            ["name" => "Paket Resolusi Anti Diabetes", "category" => "Umum"],
            ["name" => "Paket PCOS Reset 5", "category" => "Umum"],
            ["name" => "Festive Season", "category" => "Umum"],
            ["name" => "Velvet Treasure", "category" => "Umum"],
            ["name" => "Symphony Serenade", "category" => "Umum"],
            ["name" => "Violet Dawn", "category" => "Umum"],
            ["name" => "Lavender Radiance Joy", "category" => "Umum"],
            ["name" => "Starlit Noel", "category" => "Umum"],
            ["name" => "Carousel d'or", "category" => "Umum"],
            ["name" => "Hampers lebaran box taj mahal", "category" => "Umum"],
            ["name" => "Hampers lebaran knot bag", "category" => "Umum"],
            ["name" => "Hampers imlek tas maroon", "category" => "Umum"],
            ["name" => "Hampers lebaran Nur Minar", "category" => "Umum"],
            ["name" => "Hampers lebaran Humayyun / mini pouch", "category" => "Umum"],
            ["name" => "Hampers lebaran Shahi Fort / anyaman", "category" => "Umum"],
            ["name" => "Hampers lebaran Jahanara / mutiara", "category" => "Umum"],
            ["name" => "Hampers lebaran Taj / Celestial / Taj Mahal", "category" => "Umum"],
            ["name" => "Hampers lebaran \u2060Mughal Royal Legacy / Luxury", "category" => "Umum"],
            ["name" => "Hampers lebaran IED Gourmet", "category" => "Umum"],
            ["name" => "Rosemary Sky Gourmet", "category" => "Umum"]
        ];

        foreach ($products as $index => $p) {
            Produk::updateOrCreate(
                ['nama_produk' => $p['name']],
                [
                    'kategori' => $p['category'],
                    'stok_produk' => 0,
                    'harga_produk' => 0,
                    'satuan' => 'pcs'
                ]
            );
        }
    }
}
